"""Added role to User

Revision ID: 3667cdd82e5d
Revises: e67709e188a8
Create Date: 2024-06-23 18:38:27.816298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3667cdd82e5d'
down_revision = 'e67709e188a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('isAdmin', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_isAdmin'), ['isAdmin'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles'), ['roles'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles'))
        batch_op.drop_index(batch_op.f('ix_user_isAdmin'))
        batch_op.drop_column('isAdmin')
        batch_op.drop_column('roles')

    # ### end Alembic commands ###
